### ISSUE TITLE
SelectSingleBinaryAndPDBControlViewModel never gets an IBinaryLocator

### ISSUE THREAD

**Issue by jonwis** [microsoft/SizeBench#22]
**Describe the bug**
Using the "pick pdb" path, the code is supposed to hunt around to find a .dll nearby when the PDB path is chosen. This hunting does not happen.

**What you are doing**
1. Start a new single-binary session
2. Pick a PDB

**Expected behavior**
After picking a PDB with a DLL next to it, the "Binary path" field should auto-populate.

**Environment Details**
 - Windows 11
 - Version 1.0.0.0 git commit 2450ddcf-dirty

**Additional context**
The callstack instantiating SelectSingleBinaryAndPDBControlViewModel is in the Windsor module. It ends up synthesizing a zero-length `IBInaryLocator` parameter to the constructor, causing `InferBinaryPathFromPDBPathIfPossible` to skip the mapping step.

**Comment by Austin-Lamb** [comment]
🎉 This is now fixed in the Store version.

You may need to go into the Store app and force an update, but it should happen in the background eventually.  The version with the fix is 2.2401.1001.0
