### ISSUE TITLE
How to contribute in About box gives 404 error

### ISSUE THREAD

**Issue by TomRuark** [microsoft/SizeBench#36]
This does not exist: https://github.com/microsoft/SizeBench/blob/main/docs/Contributing.md

**Comment by Austin-Lamb** [comment]
Oh thanks!  The `/docs/` isn't necessary, I'll see about updating the link in the UI.  That file moved up a level when porting this code from the internal repo to GitHub and I missed this one.

**Comment by Austin-Lamb** [comment]
And apparently GitHub is case-sensitive so it needs to be `CONTRIBUTING.md`

**Comment by Austin-Lamb** [comment]
🎉 This is now deployed to the Store, with version 2.2403.1500.0

You may need to check for updates explicitly in the Microsoft Store for this to download promptly.
