### ISSUE TITLE
crash when parse delay load table in 32bit dll

### ISSUE THREAD

**Issue by darknesswind** [microsoft/SizeBench#40]
src/SizeBench.AnalysisEngine/PE/PEFile.cs : 511
thunk32 deref twice (use nameTableThunkRva) but only once (use nameTableThunkPtrRva) need

[delayLoad.zip](https://github.com/microsoft/SizeBench/files/14944075/delayLoad.zip)

```[tasklist]
### Tasks
```

**Comment by Austin-Lamb** [comment]
Is there a 32-bit DLL I can try this on to repro?  If you don't have anything publicly shareable but can share privately, let me know and we can figure that out.

**Comment by darknesswind** [comment]
> Is there a 32-bit DLL I can try this on to repro? If you don't have anything publicly shareable but can share privately, let me know and we can figure that out.

I Uploaded the demo

**Comment by Austin-Lamb** [comment]
I can repro this locally, I'm working on a fix - thank you for providing the repro!

**Comment by Austin-Lamb** [comment]
🎉 @darknesswind, the fixed version is now deployed to the Store now.

You may need to go into the Store app and click "get updates" to force it to update immediately.  The fixed version is 2.2404.1801.0

Thank you for reporting this!
